version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    restart: always
    depends_on:
      - redis
      - postgres
    networks:
      - local-network

  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.tasks.celery_worker worker --pool=solo --loglevel=info
    environment:
      - ENVIRONMENT=production
    restart: always
    depends_on:
      - redis
      - postgres
      - api
    networks:
      - local-network

  celery_beat:
    container_name: celery_beat
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.tasks.celery_worker beat --loglevel=INFO
    environment:
      - ENVIRONMENT=production
    restart: always
    depends_on:
      - redis
      - postgres
      - api
    networks:
      - local-network

  flower:
    container_name: flower
    build: .
    command: celery -A app.tasks.celery_worker flower --port=5555
    ports:
      - 5556:5555
    restart: always
    depends_on:
      - api
      - redis
      - celery_worker
    networks:
      - local-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - local-network
  
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=books
    networks:
      - local-network

networks:
  local-network: